3 get /api/categories
dreamingOfSoy/nc-games-api pull request #1
Opened 2023-03-27 14:04 UTC by dreamingOfSoy

2023-03-27 14:29 UTC, itskatherine requested changes
Hi James, a great start - could you please have a look over my comments and resubmit this PR once you've addressed them 🙂

2023-03-27 14:29 UTC, itskatherine commented on __tests__/app.test.js
> +
Nice test, good that you're checking the length of the array to prevent false positives 🙌

2023-03-27 14:29 UTC, itskatherine commented on __tests__/app.test.js
> +  });
Missing a sad path test for a bad path such as `/api/toopics` or `/api/katherine` for example
Could you please add in this test and make sure it passes

2023-03-27 14:29 UTC, itskatherine commented on app.js
> +app.use(express.json());
We don't need this line yet as it lets us access the body for a post request
It's best practise to only include code that's needed to meet the requirements of the specific ticket so remove it for this PR please

2023-03-27 14:29 UTC, itskatherine commented on app.js
> +    error: `${req.originalUrl} is not available on this server`,
I haven't seen `originalUrl` used before, cool!

2023-03-27 14:29 UTC, itskatherine commented on __tests__/categoryModel.test.js
> +});
This file isn't needed, all you need to test is what is returned from the endpoint `/api/categories` (which you've made a great start on in your app.test.js file 👍 ) 
You can also test util functions if you add them at any point in the project, but you don't need tests for your model functions.

2023-03-27 14:29 UTC, itskatherine commented on models/categoryModel.js
> +class Category {
Not sure why you're making a class here James 🤔 , this just needs to be a model function. You then wouldn't need to use the .find method of this class, you could just run the function.

2023-03-27 14:29 UTC, itskatherine commented on app.js
> +app.use(errorHandler);
This error handling middleware isn't currently being used on this ticket so can be removed (to make sure only code related to this ticket is being submitted in this PR)

2023-03-27 14:52 UTC, dreamingOfSoy commented on models/categoryModel.js
> +class Category {
Hi Catherine, I just like the syntax for when there are more model functions, I can write Catergory.find for finding catergories, or Review.find for finding reviews.

2023-03-27 14:53 UTC, dreamingOfSoy commented on app.js
> +app.use(errorHandler);
Hi Catherine, I've kept this in, as this is what captures my next in the all callback above it and returns the error. Is this okay?

2023-03-27 15:00 UTC, NRMSMITH commented on models/categoryModel.js
> +class Category {
Classes are inappropriate for this sprint as you are required to use supertest. Ignoring architectural models like MVC leads to messy code that is unreadable for others.

2023-03-27 15:05 UTC, NRMSMITH requested changes
- please review the comments made and make the changes before submitting another pr

2023-03-27 15:05 UTC, NRMSMITH commented on __tests__/app.test.js
> +        expect(error).toBe("/api/wrong-path is not available on this server");
lovely specific message

2023-03-27 15:05 UTC, NRMSMITH commented on app.js
> +app.use(errorHandler);
At some point you will need to refactor this, as you will have more error handling to do, and creating a new variable to be passed to your errorHandler repeatedly will become cumbersome. I would consider refactoring it now so that you res.send in the above error handler, rather than passing it to another.

2023-03-27 15:18 UTC, dreamingOfSoy commented on models/categoryModel.js
> +class Category {
Hi Niamh, okay, I'll change it to a functional approach. However, I'm a little confused, why are classes inappropriate when using supertest, also why is using a class based model over exporting individual model functions ignoring MVC?

2023-03-28 10:23 UTC, NRMSMITH commented on models/categoryModel.js
> +class Category {
It's just a really uncommon way of doing this - functional programming is more popular than OOP is for express and js in general. It's more beneficial to show that you can do functional programming to build servers.

2023-03-28 10:23 UTC, NRMSMITH commented
🚀 Happy to merge!

2023-03-28 10:31 UTC, merged